name: qubic
channels:
    - defaults
    - conda-forge
dependencies:
    - numpy>1.2
    - scipy>1.7
    - scikit-learn
    - matplotlib
    - pyserial
    - pyusb
    - pip
    #optional
    - antlr4-python3-runtime

#to create environment:
#   conda env create -f condaenv.yml
#
# this will create a new environment called qubic
